### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by stef204** [ohwgiles/scappit#3]
% make
[ 16%] Automatic moc for target scappit
[ 16%] Built target scappit_automoc
[ 33%] Building CXX object CMakeFiles/scappit.dir/scappit.cpp.o
~/scappit.cpp: In member function ‘QPointF Arrow::vertex(qreal, qreal) const’:
~/scappit/scappit.cpp:124:82: error: ‘M_PI’ was not declared in this scope
             line.p1().x() + (line.length() \* mhyp) \* cos((line.angle() + dang) \* M_PI / 180.0),
                                                                                  ^~~~
~/scappit/scappit.cpp:124:94: error: ‘cos’ was not declared in this scope
             line.p1().x() + (line.length() \* mhyp) \* cos((line.angle() + dang) \* M_PI / 180.0),
                                                                                              ^
~/scappit/scappit.cpp:125:94: error: ‘sin’ was not declared in this scope
             line.p1().y() - (line.length() \* mhyp) \* sin((line.angle() + dang) \* M_PI / 180.0)
                                                                                              ^
make[2]: **\* [CMakeFiles/scappit.dir/build.make:72: CMakeFiles/scappit.dir/scappit.cpp.o] Error 1
make[1]: **\* [CMakeFiles/Makefile2:68: CMakeFiles/scappit.dir/all] Error 2
make: **\* [Makefile:128: all] Error 2

**Comment by ohwgiles** [comment]
thanks, fixed
